### PR TITLE
fix: Use translate value in calculation (#72)

### PR DESCRIPTION
**Pull request by thetravis**
This seems to fix the issue I've been having when using the directive in combination with angular2-draggable.

### CODE REVIEW

**Comment by mattlewis92** [comment]
So sorry about the late reply on this one, I've not had much time for open source lately. I will cut a release shortly with this PR. Thanks for your contribution! 🎉

**Comment by thetravis** [comment]
I see you improved my solution :)

**Comment by mattlewis92** [comment]
Hope that was ok, you've already been waiting over a month and I didn't want to drag it out any longer by just reviewing instead of merging 😄

**Comment by thetravis** [comment]
Don't worry. I just made a dirty fix for my project as it needed to be fixed and I didn't care how at the moment.  I'm rather new to web development also. My point was to address this issue and provide a solution of some sort :) Thank you, I think I can soon switch to back to the repo version.

**Pull request merged**
