### PR TITLE
fix: check onMouseDown event is cancelable before calling event.preventDefault()

### PR DESCRIPTION
**Pull request by danhobbs75**
The same test as for the resizable directive to stop console warnings being shown when calling preventDefault()

### CODE REVIEW

**Comment by danhobbs75** [comment]
I can see it's still got 5 commits from the previous PR. I'm not sure how that's happened. I did update my forked repo from this one before making the commit with the latest one-line change. I'm not sure how to delete them, or if that's even the right thing to do. Please feel free to reject the PR if I need to do something else on my fork repo first.

**Review by mattlewis92 — APPROVED** [review]
Thank you!!

**Comment by mattlewis92** [comment]
> I can see it's still got 5 commits from the previous PR. I'm not sure how that's happened. I did update my forked repo from this one before making the commit with the latest one-line change. I'm not sure how to delete them, or if that's even the right thing to do. Please feel free to reject the PR if I need to do something else on my fork repo first.

You're good! I'll be squash merging this so as long as the "Files changed" tab is correct we don't need to worry about the git history 😄

**Comment by mattlewis92** [comment]
Released as `7.0.2`!

**Comment by danhobbs75** [comment]
> Released as `7.0.2`!

NOW it's working smoothly. Thanks for dealing with the merge admin again. :-)

**Comment by mattlewis92** [comment]
> > Released as `7.0.2`!
> 
> NOW it's working smoothly. Thanks for dealing with the merge admin again. :-)

This makes more sense to me now, as the try catch should have been silencing this error. But I guess we missed this place 😄

**Comment by danhobbs75** [comment]
> > > Released as `7.0.2`!
> > 
> > 
> > NOW it's working smoothly. Thanks for dealing with the merge admin again. :-)
> 
> This makes more sense to me now, as the try catch should have been silencing this error. But I guess we missed this place 😄

It looks like the behaviour is that try/catch will stop an error going to the console, but warnings are still reported.

And I do recall that I noticed this second instance when I first looked at the code, but in between getting to grips with everything else (plus it was already late on Sunday night) I forgot about it. Oh well. I did also learn that spurious error messages from git were really caused by me not following commit naming standards (the 'fix:' prefix was missing initially) and I wasted a LOT of time reinstalling git because the error message made it appear that cygwin was missing. A classic developer tale of woe solved by actually reading the output from git which gave the game away.

**Pull request merged**
