### PR TITLE
Fix: keep cursor while resizing

### PR DESCRIPTION
**Pull request by bertofer**
Fixes https://github.com/mattlewis92/angular-resizable-element/issues/33

### CODE REVIEW

**Comment by mattlewis92** [comment]
Oh there's merge conflicts after the other PR, can you [sync with master](https://help.github.com/articles/syncing-a-fork/)? Thanks! 😄

**Comment by mattlewis92** [comment]
Perfect, thanks! 😃

**Comment by mattlewis92** [comment]
Released at 0.5.5, thanks for the contributions! :octocat:

**Comment by bertofer** [comment]
Thanks for the work on this repo, very useful !

Cheers

**Pull request merged**
