### PR TITLE
fix: copy canvas when using `enableGhostResize`

### PR DESCRIPTION
**Pull request by JBeen**
Copy all content of resized node, includes canvas.
Use implementation deepCloneNode from @angular/cdk 11.0

### CODE REVIEW

**Comment by mattlewis92** [comment]
Nice one, thanks for this! Would you be able to take a go at adding a [test](https://github.com/mattlewis92/angular-resizable-element/blob/master/test/resizable.spec.ts) for it as well? I think we can use the code you added to the demo as a test case and then we just need to assert that the ghost element has the canvas text inside it while resizing. Let me know if that makes sense or you need any help! 🙌

**Comment by JBeen** [comment]
Ok. I added test. I used canvas.toDataURL() to check canvas inner data.

**Review by mattlewis92 — APPROVED** [review]
LGTM, thanks a lot!!

**Comment by mattlewis92** [comment]
Released as `4.0.0`, thanks for your contribution! 🥳

**Pull request merged**
