### PR TITLE
feat(cssClasses): Gives classes to main element depend on state

### PR DESCRIPTION
**Pull request by Vi-dot**
Gives css classes to main element to easily change design depending on current state.
- resize-hover (when cursor is shown)
- resize-active (when resizing)
- resize-left /-right / -top / -bottom (to know which edge is activated)

### CODE REVIEW

**Comment by mattlewis92** [comment]
Awesome, thank you! 👍

**Comment by Vi-dot** [comment]
But this one is not perfect, the class `resize-active` has some bugs.

**Comment by mattlewis92** [comment]
Ah yes, this should fix it: https://github.com/mattlewis92/angular-resizable-element/commit/1427eec0568c6bc0bb422ab0447d7794cdfcf4be

**Comment by mattlewis92** [comment]
Released as 0.7.0 🎉

**Comment by Vi-dot** [comment]
Fast integration ! Thanks :+1:

**Comment by mickeyjohn** [comment]
Thanks for the great works.
I found it only changes the main div's style with 'resize-active' class specified only. How are other classes work?

Thanks.

**Pull request merged**
